### ISSUE TITLE
Documentation needed for using `cast` for comma separated lists

### ISSUE THREAD

**Issue by edmorley** [rconradharris/envparse#1]
Using envparse 0.16 on Python 2.7:

```bash
$ export foo="abc,def"
$ python
...
>>> from envparse import env
>>> env("foo", cast=list)
['a', 'b', 'c', ',', 'd', 'e', 'f']
```

Whereas I would have expected:
`['abc', 'def']`

Am I doing something wrong, or is this a bug?

**Comment by russelldavies** [comment]
It's not documented but you need to pass in a subtype as a list, e.g.`env('foo', cast=[str])` will work.

**Comment by edmorley** [comment]
Ah indeed, thank you :-)

Leaving this open for documenting.

**Comment by sloria** [comment]
The API for this has changed. You now should pass the `subtype` argument

```python
env('foo', type=list, subtype=int)
```

This is documented in the README, so I think this issue can be closed.

**Comment by rconradharris** [comment]
Agree with @sloria think this can be closed since we changed the API here.
